services:
  app:
    build: .

    env_file:
      - .env
    environment:
      - APP_SERVER_HOST=0.0.0.0
      - APP_SERVER_PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./static:/app/static
      - ./src/templates:/app/src/templates
